# 1. 基础配置 - 确保仓库名大小写与 GitHub 一致，末尾带斜杠
baseURL = "https://younbrian.github.io/MyBlog/"
languageCode = 'zh-cn'
title = 'Younbrian’s Blog'
theme = 'FixIt'
paginate = 20
buildFuture = true
[outputs]
  home = ["HTML", "RSS","JSON"]
  page = ["HTML"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # 允许在 Markdown 中直接书写 HTML（对嵌入 Payload 或自定义样式很有用）
      unsafe = true 
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai" 

[params]
  # FixIt 核心参数
  version = "0.3.x"
  dateFormat = "2006-01-02"
  enableGitInfo = true
  relativeURLs = false
  canonifyURLs = true

  keywords = ["CTF", "WebSecurity"]
  
  # 资源管理（解决子目录下样式不加载的关键）
  [params.asset]
    fingerprint = false

  # 全局作者信息
  [params.author]
    name = "Younbrian"
    avatar = "images/avatar.jpg" 

  [params.section]
    # 归档页面配置
    [params.section.archives]
      enable = false
      paginate = 20
      expand = true
      type = "posts"
  [params.page]
    # 文章顶部元数据显示
    [params.page.header]
      author = true
      avatar= false
      date = true
      categories = true
      tags = true
    
  [params.home]
    # 首页副标题，支持简单的 Markdown
    subtitle = "Cyber Security Researcher & CTF Player"
    # 是否显示社交链接
    social = true
    # 首页文章列表的显示模式 ("posts" 显示文章列表, "profile" 仅显示个人信息)
    type = "posts"
    [params.home.profile]
      enable = true
      # 你的头像路径（由于我们设置了相对路径，确保 images/avatar.jpg 存在）
      avatarURL = "images/avatar.jpg"
      title = "Younbrian"
      subtitle = "Yoo | 信息安全研究"
      # 是否显示打字机效果
      typeit = true
      # 是否显示社交图标
      social = true
  [params.social]
    GitHub = "YounBrian"
    Email = "Younbrian886@163.com"
  

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[menu.main]]
  identifier = "categories"
  name = "分类"
  url = "categories"
  weight = 2
  pre = "<i class='fa-solid fa-folder-open fa-fw'></i>"

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "tags"
  weight = 3
  pre = "<i class='fa-solid fa-tags fa-fw'></i>"