name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"] # 确保你的本地分支名也是 main（Windows 以前默认叫 master）

permissions:
  contents: read
  pages: write
  id-token: write

# 避免重复构建，如果上一个还没跑完就推了新的，会自动取消旧的
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true # FixIt 主题必须使用扩展版来处理 SCSS

      - name: Build with Hugo
        # 建议增加 --gc 清理缓存，--minify 压缩体积
        run: hugo --gc --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4